/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _COMPUTE_H_RPCGEN
#define _COMPUTE_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct operands {
	int a;
	int b;
};
typedef struct operands operands;

#define COMP_PROG 0x20000002
#define COMP_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define ADD 1
extern  int * add_1(operands *, CLIENT *);
extern  int * add_1_svc(operands *, struct svc_req *);
#define SUB 2
extern  int * sub_1(operands *, CLIENT *);
extern  int * sub_1_svc(operands *, struct svc_req *);
#define MUL 3
extern  int * mul_1(operands *, CLIENT *);
extern  int * mul_1_svc(operands *, struct svc_req *);
#define DIV 4
extern  int * div_1(operands *, CLIENT *);
extern  int * div_1_svc(operands *, struct svc_req *);
extern int comp_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define ADD 1
extern  int * add_1();
extern  int * add_1_svc();
#define SUB 2
extern  int * sub_1();
extern  int * sub_1_svc();
#define MUL 3
extern  int * mul_1();
extern  int * mul_1_svc();
#define DIV 4
extern  int * div_1();
extern  int * div_1_svc();
extern int comp_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_operands (XDR *, operands*);

#else /* K&R C */
extern bool_t xdr_operands ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_COMPUTE_H_RPCGEN */
