package MatrixOpsApp;


/**
* MatrixOpsApp/_MatrixOpsStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from MatrixOps.idl
* Saturday, 6 December 2025 23:48:17 o'clock WAT
*/


// MatrixOps interface
public class _MatrixOpsStub extends org.omg.CORBA.portable.ObjectImpl implements MatrixOpsApp.MatrixOps
{


  // Add two matrices
  public double[][] add (double[][] m1, double[][] m2) throws MatrixOpsApp.IncompatibleDimensions, MatrixOpsApp.InvalidMatrix
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("add", true);
                MatrixOpsApp.MatrixHelper.write ($out, m1);
                MatrixOpsApp.MatrixHelper.write ($out, m2);
                $in = _invoke ($out);
                double $result[][] = MatrixOpsApp.MatrixHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:MatrixOpsApp/IncompatibleDimensions:1.0"))
                    throw MatrixOpsApp.IncompatibleDimensionsHelper.read ($in);
                else if (_id.equals ("IDL:MatrixOpsApp/InvalidMatrix:1.0"))
                    throw MatrixOpsApp.InvalidMatrixHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return add (m1, m2        );
            } finally {
                _releaseReply ($in);
            }
  } // add


  // Multiply two matrices
  public double[][] multiply (double[][] m1, double[][] m2) throws MatrixOpsApp.IncompatibleDimensions, MatrixOpsApp.InvalidMatrix
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("multiply", true);
                MatrixOpsApp.MatrixHelper.write ($out, m1);
                MatrixOpsApp.MatrixHelper.write ($out, m2);
                $in = _invoke ($out);
                double $result[][] = MatrixOpsApp.MatrixHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:MatrixOpsApp/IncompatibleDimensions:1.0"))
                    throw MatrixOpsApp.IncompatibleDimensionsHelper.read ($in);
                else if (_id.equals ("IDL:MatrixOpsApp/InvalidMatrix:1.0"))
                    throw MatrixOpsApp.InvalidMatrixHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return multiply (m1, m2        );
            } finally {
                _releaseReply ($in);
            }
  } // multiply


  // Transpose a matrix
  public double[][] transpose (double[][] m) throws MatrixOpsApp.InvalidMatrix
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("transpose", true);
                MatrixOpsApp.MatrixHelper.write ($out, m);
                $in = _invoke ($out);
                double $result[][] = MatrixOpsApp.MatrixHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:MatrixOpsApp/InvalidMatrix:1.0"))
                    throw MatrixOpsApp.InvalidMatrixHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return transpose (m        );
            } finally {
                _releaseReply ($in);
            }
  } // transpose


  // Calculate trace of a matrix (sum of diagonal elements)
  public double trace (double[][] m) throws MatrixOpsApp.InvalidMatrix
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("trace", true);
                MatrixOpsApp.MatrixHelper.write ($out, m);
                $in = _invoke ($out);
                double $result = $in.read_double ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:MatrixOpsApp/InvalidMatrix:1.0"))
                    throw MatrixOpsApp.InvalidMatrixHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return trace (m        );
            } finally {
                _releaseReply ($in);
            }
  } // trace

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:MatrixOpsApp/MatrixOps:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _MatrixOpsStub
