package MatrixOpsApp;


/**
* MatrixOpsApp/IncompatibleDimensions.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from MatrixOps.idl
* Saturday, 6 December 2025 23:48:17 o'clock WAT
*/

public final class IncompatibleDimensions extends org.omg.CORBA.UserException
{
  public String reason = null;

  public IncompatibleDimensions ()
  {
    super(IncompatibleDimensionsHelper.id());
  } // ctor

  public IncompatibleDimensions (String _reason)
  {
    super(IncompatibleDimensionsHelper.id());
    reason = _reason;
  } // ctor


  public IncompatibleDimensions (String $reason, String _reason)
  {
    super(IncompatibleDimensionsHelper.id() + "  " + $reason);
    reason = _reason;
  } // ctor

} // class IncompatibleDimensions
