package MatrixOpsApp;

/**
* MatrixOpsApp/IncompatibleDimensionsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from MatrixOps.idl
* Saturday, 6 December 2025 23:48:17 o'clock WAT
*/

public final class IncompatibleDimensionsHolder implements org.omg.CORBA.portable.Streamable
{
  public MatrixOpsApp.IncompatibleDimensions value = null;

  public IncompatibleDimensionsHolder ()
  {
  }

  public IncompatibleDimensionsHolder (MatrixOpsApp.IncompatibleDimensions initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = MatrixOpsApp.IncompatibleDimensionsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    MatrixOpsApp.IncompatibleDimensionsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return MatrixOpsApp.IncompatibleDimensionsHelper.type ();
  }

}
