package MatrixOpsApp;


/**
* MatrixOpsApp/InvalidMatrix.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from MatrixOps.idl
* Saturday, 6 December 2025 23:48:17 o'clock WAT
*/

public final class InvalidMatrix extends org.omg.CORBA.UserException
{
  public String reason = null;

  public InvalidMatrix ()
  {
    super(InvalidMatrixHelper.id());
  } // ctor

  public InvalidMatrix (String _reason)
  {
    super(InvalidMatrixHelper.id());
    reason = _reason;
  } // ctor


  public InvalidMatrix (String $reason, String _reason)
  {
    super(InvalidMatrixHelper.id() + "  " + $reason);
    reason = _reason;
  } // ctor

} // class InvalidMatrix
