package MatrixOpsApp;

/**
* MatrixOpsApp/InvalidMatrixHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from MatrixOps.idl
* Saturday, 6 December 2025 23:48:17 o'clock WAT
*/

public final class InvalidMatrixHolder implements org.omg.CORBA.portable.Streamable
{
  public MatrixOpsApp.InvalidMatrix value = null;

  public InvalidMatrixHolder ()
  {
  }

  public InvalidMatrixHolder (MatrixOpsApp.InvalidMatrix initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = MatrixOpsApp.InvalidMatrixHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    MatrixOpsApp.InvalidMatrixHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return MatrixOpsApp.InvalidMatrixHelper.type ();
  }

}
