package MatrixOpsApp;


/**
* MatrixOpsApp/MatrixOpsHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from MatrixOps.idl
* Saturday, 6 December 2025 23:48:17 o'clock WAT
*/


// MatrixOps interface
abstract public class MatrixOpsHelper
{
  private static String  _id = "IDL:MatrixOpsApp/MatrixOps:1.0";

  public static void insert (org.omg.CORBA.Any a, MatrixOpsApp.MatrixOps that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static MatrixOpsApp.MatrixOps extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (MatrixOpsApp.MatrixOpsHelper.id (), "MatrixOps");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static MatrixOpsApp.MatrixOps read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_MatrixOpsStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, MatrixOpsApp.MatrixOps value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static MatrixOpsApp.MatrixOps narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof MatrixOpsApp.MatrixOps)
      return (MatrixOpsApp.MatrixOps)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      MatrixOpsApp._MatrixOpsStub stub = new MatrixOpsApp._MatrixOpsStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static MatrixOpsApp.MatrixOps unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof MatrixOpsApp.MatrixOps)
      return (MatrixOpsApp.MatrixOps)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      MatrixOpsApp._MatrixOpsStub stub = new MatrixOpsApp._MatrixOpsStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
