package MatrixOpsApp;


/**
* MatrixOpsApp/MatrixHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from MatrixOps.idl
* Saturday, 6 December 2025 23:48:17 o'clock WAT
*/

public final class MatrixHolder implements org.omg.CORBA.portable.Streamable
{
  public double value[][] = null;

  public MatrixHolder ()
  {
  }

  public MatrixHolder (double[][] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = MatrixOpsApp.MatrixHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    MatrixOpsApp.MatrixHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return MatrixOpsApp.MatrixHelper.type ();
  }

}
