package MatrixOpsApp;


/**
* MatrixOpsApp/MatrixOpsPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from MatrixOps.idl
* Saturday, 6 December 2025 23:48:17 o'clock WAT
*/


// MatrixOps interface
public abstract class MatrixOpsPOA extends org.omg.PortableServer.Servant
 implements MatrixOpsApp.MatrixOpsOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("add", new java.lang.Integer (0));
    _methods.put ("multiply", new java.lang.Integer (1));
    _methods.put ("transpose", new java.lang.Integer (2));
    _methods.put ("trace", new java.lang.Integer (3));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {

  // Add two matrices
       case 0:  // MatrixOpsApp/MatrixOps/add
       {
         try {
           double m1[][] = MatrixOpsApp.MatrixHelper.read (in);
           double m2[][] = MatrixOpsApp.MatrixHelper.read (in);
           double $result[][] = null;
           $result = this.add (m1, m2);
           out = $rh.createReply();
           MatrixOpsApp.MatrixHelper.write (out, $result);
         } catch (MatrixOpsApp.IncompatibleDimensions $ex) {
           out = $rh.createExceptionReply ();
           MatrixOpsApp.IncompatibleDimensionsHelper.write (out, $ex);
         } catch (MatrixOpsApp.InvalidMatrix $ex) {
           out = $rh.createExceptionReply ();
           MatrixOpsApp.InvalidMatrixHelper.write (out, $ex);
         }
         break;
       }


  // Multiply two matrices
       case 1:  // MatrixOpsApp/MatrixOps/multiply
       {
         try {
           double m1[][] = MatrixOpsApp.MatrixHelper.read (in);
           double m2[][] = MatrixOpsApp.MatrixHelper.read (in);
           double $result[][] = null;
           $result = this.multiply (m1, m2);
           out = $rh.createReply();
           MatrixOpsApp.MatrixHelper.write (out, $result);
         } catch (MatrixOpsApp.IncompatibleDimensions $ex) {
           out = $rh.createExceptionReply ();
           MatrixOpsApp.IncompatibleDimensionsHelper.write (out, $ex);
         } catch (MatrixOpsApp.InvalidMatrix $ex) {
           out = $rh.createExceptionReply ();
           MatrixOpsApp.InvalidMatrixHelper.write (out, $ex);
         }
         break;
       }


  // Transpose a matrix
       case 2:  // MatrixOpsApp/MatrixOps/transpose
       {
         try {
           double m[][] = MatrixOpsApp.MatrixHelper.read (in);
           double $result[][] = null;
           $result = this.transpose (m);
           out = $rh.createReply();
           MatrixOpsApp.MatrixHelper.write (out, $result);
         } catch (MatrixOpsApp.InvalidMatrix $ex) {
           out = $rh.createExceptionReply ();
           MatrixOpsApp.InvalidMatrixHelper.write (out, $ex);
         }
         break;
       }


  // Calculate trace of a matrix (sum of diagonal elements)
       case 3:  // MatrixOpsApp/MatrixOps/trace
       {
         try {
           double m[][] = MatrixOpsApp.MatrixHelper.read (in);
           double $result = (double)0;
           $result = this.trace (m);
           out = $rh.createReply();
           out.write_double ($result);
         } catch (MatrixOpsApp.InvalidMatrix $ex) {
           out = $rh.createExceptionReply ();
           MatrixOpsApp.InvalidMatrixHelper.write (out, $ex);
         }
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:MatrixOpsApp/MatrixOps:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public MatrixOps _this() 
  {
    return MatrixOpsHelper.narrow(
    super._this_object());
  }

  public MatrixOps _this(org.omg.CORBA.ORB orb) 
  {
    return MatrixOpsHelper.narrow(
    super._this_object(orb));
  }


} // class MatrixOpsPOA
