package MatrixOpsApp;


/**
* MatrixOpsApp/MatrixOpsOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from MatrixOps.idl
* Saturday, 6 December 2025 23:48:17 o'clock WAT
*/


// MatrixOps interface
public interface MatrixOpsOperations 
{

  // Add two matrices
  double[][] add (double[][] m1, double[][] m2) throws MatrixOpsApp.IncompatibleDimensions, MatrixOpsApp.InvalidMatrix;

  // Multiply two matrices
  double[][] multiply (double[][] m1, double[][] m2) throws MatrixOpsApp.IncompatibleDimensions, MatrixOpsApp.InvalidMatrix;

  // Transpose a matrix
  double[][] transpose (double[][] m) throws MatrixOpsApp.InvalidMatrix;

  // Calculate trace of a matrix (sum of diagonal elements)
  double trace (double[][] m) throws MatrixOpsApp.InvalidMatrix;
} // interface MatrixOpsOperations
