package MatrixOpsApp;


/**
* MatrixOpsApp/MatrixOps.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from MatrixOps.idl
* Saturday, 6 December 2025 23:48:17 o'clock WAT
*/


// MatrixOps interface
public interface MatrixOps extends MatrixOpsOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface MatrixOps
