package MatrixOpsApp;

/**
* MatrixOpsApp/MatrixOpsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from MatrixOps.idl
* Saturday, 6 December 2025 23:48:17 o'clock WAT
*/


// MatrixOps interface
public final class MatrixOpsHolder implements org.omg.CORBA.portable.Streamable
{
  public MatrixOpsApp.MatrixOps value = null;

  public MatrixOpsHolder ()
  {
  }

  public MatrixOpsHolder (MatrixOpsApp.MatrixOps initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = MatrixOpsApp.MatrixOpsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    MatrixOpsApp.MatrixOpsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return MatrixOpsApp.MatrixOpsHelper.type ();
  }

}
