package MatrixOpsApp;


/**
* MatrixOpsApp/RowHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from MatrixOps.idl
* Saturday, 6 December 2025 23:48:17 o'clock WAT
*/


// Matrix type: sequence of sequences of doubles
public final class RowHolder implements org.omg.CORBA.portable.Streamable
{
  public double value[] = null;

  public RowHolder ()
  {
  }

  public RowHolder (double[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = MatrixOpsApp.RowHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    MatrixOpsApp.RowHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return MatrixOpsApp.RowHelper.type ();
  }

}
