package AddressBookApp;


/**
* AddressBookApp/_AddressBookStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from AddressBook.idl
* Saturday, 6 December 2025 23:38:13 o'clock WAT
*/


// AddressBook interface
public class _AddressBookStub extends org.omg.CORBA.portable.ObjectImpl implements AddressBookApp.AddressBook
{


  // Add a new contact
  public void addContact (AddressBookApp.Contact contact) throws AddressBookApp.DuplicateContact
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("addContact", true);
                AddressBookApp.ContactHelper.write ($out, contact);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:AddressBookApp/DuplicateContact:1.0"))
                    throw AddressBookApp.DuplicateContactHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                addContact (contact        );
            } finally {
                _releaseReply ($in);
            }
  } // addContact


  // Remove a contact by name
  public void removeContact (String name) throws AddressBookApp.ContactNotFound
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("removeContact", true);
                $out.write_string (name);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:AddressBookApp/ContactNotFound:1.0"))
                    throw AddressBookApp.ContactNotFoundHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                removeContact (name        );
            } finally {
                _releaseReply ($in);
            }
  } // removeContact


  // Get a contact by name
  public AddressBookApp.Contact getContact (String name) throws AddressBookApp.ContactNotFound
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getContact", true);
                $out.write_string (name);
                $in = _invoke ($out);
                AddressBookApp.Contact $result = AddressBookApp.ContactHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                if (_id.equals ("IDL:AddressBookApp/ContactNotFound:1.0"))
                    throw AddressBookApp.ContactNotFoundHelper.read ($in);
                else
                    throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getContact (name        );
            } finally {
                _releaseReply ($in);
            }
  } // getContact


  // List all contacts
  public AddressBookApp.Contact[] listContacts ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("listContacts", true);
                $in = _invoke ($out);
                AddressBookApp.Contact $result[] = AddressBookApp.ContactListHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return listContacts (        );
            } finally {
                _releaseReply ($in);
            }
  } // listContacts

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:AddressBookApp/AddressBook:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _AddressBookStub
