package AddressBookApp;


/**
* AddressBookApp/AddressBookPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from AddressBook.idl
* Saturday, 6 December 2025 23:38:13 o'clock WAT
*/


// AddressBook interface
public abstract class AddressBookPOA extends org.omg.PortableServer.Servant
 implements AddressBookApp.AddressBookOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("addContact", new java.lang.Integer (0));
    _methods.put ("removeContact", new java.lang.Integer (1));
    _methods.put ("getContact", new java.lang.Integer (2));
    _methods.put ("listContacts", new java.lang.Integer (3));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {

  // Add a new contact
       case 0:  // AddressBookApp/AddressBook/addContact
       {
         try {
           AddressBookApp.Contact contact = AddressBookApp.ContactHelper.read (in);
           this.addContact (contact);
           out = $rh.createReply();
         } catch (AddressBookApp.DuplicateContact $ex) {
           out = $rh.createExceptionReply ();
           AddressBookApp.DuplicateContactHelper.write (out, $ex);
         }
         break;
       }


  // Remove a contact by name
       case 1:  // AddressBookApp/AddressBook/removeContact
       {
         try {
           String name = in.read_string ();
           this.removeContact (name);
           out = $rh.createReply();
         } catch (AddressBookApp.ContactNotFound $ex) {
           out = $rh.createExceptionReply ();
           AddressBookApp.ContactNotFoundHelper.write (out, $ex);
         }
         break;
       }


  // Get a contact by name
       case 2:  // AddressBookApp/AddressBook/getContact
       {
         try {
           String name = in.read_string ();
           AddressBookApp.Contact $result = null;
           $result = this.getContact (name);
           out = $rh.createReply();
           AddressBookApp.ContactHelper.write (out, $result);
         } catch (AddressBookApp.ContactNotFound $ex) {
           out = $rh.createExceptionReply ();
           AddressBookApp.ContactNotFoundHelper.write (out, $ex);
         }
         break;
       }


  // List all contacts
       case 3:  // AddressBookApp/AddressBook/listContacts
       {
         AddressBookApp.Contact $result[] = null;
         $result = this.listContacts ();
         out = $rh.createReply();
         AddressBookApp.ContactListHelper.write (out, $result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:AddressBookApp/AddressBook:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public AddressBook _this() 
  {
    return AddressBookHelper.narrow(
    super._this_object());
  }

  public AddressBook _this(org.omg.CORBA.ORB orb) 
  {
    return AddressBookHelper.narrow(
    super._this_object(orb));
  }


} // class AddressBookPOA
