package AddressBookApp;


/**
* AddressBookApp/AddressBookOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from AddressBook.idl
* Saturday, 6 December 2025 23:38:13 o'clock WAT
*/


// AddressBook interface
public interface AddressBookOperations 
{

  // Add a new contact
  void addContact (AddressBookApp.Contact contact) throws AddressBookApp.DuplicateContact;

  // Remove a contact by name
  void removeContact (String name) throws AddressBookApp.ContactNotFound;

  // Get a contact by name
  AddressBookApp.Contact getContact (String name) throws AddressBookApp.ContactNotFound;

  // List all contacts
  AddressBookApp.Contact[] listContacts ();
} // interface AddressBookOperations
