package AddressBookApp;


/**
* AddressBookApp/AddressBook.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from AddressBook.idl
* Saturday, 6 December 2025 23:38:13 o'clock WAT
*/


// AddressBook interface
public interface AddressBook extends AddressBookOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface AddressBook
