package AddressBookApp;

/**
* AddressBookApp/AddressBookHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from AddressBook.idl
* Saturday, 6 December 2025 23:38:13 o'clock WAT
*/


// AddressBook interface
public final class AddressBookHolder implements org.omg.CORBA.portable.Streamable
{
  public AddressBookApp.AddressBook value = null;

  public AddressBookHolder ()
  {
  }

  public AddressBookHolder (AddressBookApp.AddressBook initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = AddressBookApp.AddressBookHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    AddressBookApp.AddressBookHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return AddressBookApp.AddressBookHelper.type ();
  }

}
