package AddressBookApp;


/**
* AddressBookApp/Contact.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from AddressBook.idl
* Saturday, 6 December 2025 23:38:13 o'clock WAT
*/

public final class Contact implements org.omg.CORBA.portable.IDLEntity
{
  public String name = null;
  public String phone = null;
  public String email = null;

  public Contact ()
  {
  } // ctor

  public Contact (String _name, String _phone, String _email)
  {
    name = _name;
    phone = _phone;
    email = _email;
  } // ctor

} // class Contact
