package AddressBookApp;


/**
* AddressBookApp/ContactListHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from AddressBook.idl
* Saturday, 6 December 2025 23:38:13 o'clock WAT
*/


// Sequence of contacts
public final class ContactListHolder implements org.omg.CORBA.portable.Streamable
{
  public AddressBookApp.Contact value[] = null;

  public ContactListHolder ()
  {
  }

  public ContactListHolder (AddressBookApp.Contact[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = AddressBookApp.ContactListHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    AddressBookApp.ContactListHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return AddressBookApp.ContactListHelper.type ();
  }

}
