package AddressBookApp;


/**
* AddressBookApp/ContactNotFound.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from AddressBook.idl
* Saturday, 6 December 2025 23:38:13 o'clock WAT
*/

public final class ContactNotFound extends org.omg.CORBA.UserException
{
  public String reason = null;

  public ContactNotFound ()
  {
    super(ContactNotFoundHelper.id());
  } // ctor

  public ContactNotFound (String _reason)
  {
    super(ContactNotFoundHelper.id());
    reason = _reason;
  } // ctor


  public ContactNotFound (String $reason, String _reason)
  {
    super(ContactNotFoundHelper.id() + "  " + $reason);
    reason = _reason;
  } // ctor

} // class ContactNotFound
