package AddressBookApp;

/**
* AddressBookApp/ContactNotFoundHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from AddressBook.idl
* Saturday, 6 December 2025 23:38:13 o'clock WAT
*/

public final class ContactNotFoundHolder implements org.omg.CORBA.portable.Streamable
{
  public AddressBookApp.ContactNotFound value = null;

  public ContactNotFoundHolder ()
  {
  }

  public ContactNotFoundHolder (AddressBookApp.ContactNotFound initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = AddressBookApp.ContactNotFoundHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    AddressBookApp.ContactNotFoundHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return AddressBookApp.ContactNotFoundHelper.type ();
  }

}
