package AddressBookApp;

/**
* AddressBookApp/DuplicateContactHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from AddressBook.idl
* Saturday, 6 December 2025 23:38:13 o'clock WAT
*/

public final class DuplicateContactHolder implements org.omg.CORBA.portable.Streamable
{
  public AddressBookApp.DuplicateContact value = null;

  public DuplicateContactHolder ()
  {
  }

  public DuplicateContactHolder (AddressBookApp.DuplicateContact initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = AddressBookApp.DuplicateContactHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    AddressBookApp.DuplicateContactHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return AddressBookApp.DuplicateContactHelper.type ();
  }

}
