package AddressBookApp;


/**
* AddressBookApp/DuplicateContact.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from AddressBook.idl
* Saturday, 6 December 2025 23:38:13 o'clock WAT
*/

public final class DuplicateContact extends org.omg.CORBA.UserException
{
  public String reason = null;

  public DuplicateContact ()
  {
    super(DuplicateContactHelper.id());
  } // ctor

  public DuplicateContact (String _reason)
  {
    super(DuplicateContactHelper.id());
    reason = _reason;
  } // ctor


  public DuplicateContact (String $reason, String _reason)
  {
    super(DuplicateContactHelper.id() + "  " + $reason);
    reason = _reason;
  } // ctor

} // class DuplicateContact
